### PR TITLE
V2

### PR DESCRIPTION
**Pull request by matthax**

### CODE REVIEW

**Comment by matthax** [comment]
Hey Ryan,
I thought I'd let you know I spent some time working on the extension and
managed to sort out just about all of the major issues. We're now using the
two databases of font icons, and additionally the paths are no longer
incorrect.
The latest stable version is here:
https://github.com/matthax/EvoHax/tree/stable I also stuck in EvoHax.crx.
To use this just to to chrome://extensions and drag the file onto the
screen area and the extension will install and should work properly.

-Matt

**Comment by ryanstull** [comment]
Matt,

Awesome! I downloaded the add on on two of my computers and it worked 
great nice work! Even on my linux machine!

I'd definitely like to continue to work on this with you guys as it 
seems like something worthwhile and is good resume building material as 
well.

One suggestion, could you rename the repository to EyeConText instead of 
EvoHax?

Thanks,

Ryan

**Comment by mjblack001** [comment]
Yeah, I think there's a lot more we can do. Totally up to keep it going.
Also good idea to rename the repository.

Did you guys see Ather's email about getting him a working copy? Should we
try to bang out some more before Friday?

Either way, remember: keep a stable branch. For the love of god, keep a
stable branch.

-Mark

**Comment by ryanstull** [comment]
Oh also we should delete the marksux branch

**Pull request closed without merging**
